apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-01-05T07:20:50Z"
  generation: 1
  labels:
    app: c8db
    cluster: sourabh-sin
    component: coordinator
    federation: sourabh
    region: sin
  name: c8db-coord
  namespace: c8
  resourceVersion: "1047188"
  uid: 076fbfca-14f5-4cd0-8d5d-47395d1ea80b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: c8db
      cluster: sourabh-sin
      component: coordinator
      federation: sourabh
      region: sin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: c8db
        cluster: sourabh-sin
        component: coordinator
        federation: sourabh
        region: sin
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - c8db
                - key: component
                  operator: In
                  values:
                  - coordinator
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MACROMETA_JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: MACROMETA_JWT_SECRET
              name: macrometa-jwt-secret
        - name: C8_DCNAME
          value: sourabh-sin
        - name: C8_MASTER
          value: "true"
        - name: C8_URL
          value: sourabh-sin.eng.macrometa.io
        - name: C8_IP
          value: 151.139.180.56
        - name: C8PULSAR_SERVICE_URL
          value: pulsar://@hostname:6650
        - name: C8PULSAR_TLS_SERVICE_URL
          value: pulsar+ssl://@hostname:6651
        - name: GLIBCPP_FORCE_NEW
          value: "1"
        - name: GLIBCXX_FORCE_NEW
          value: "1"
        - name: C8DB_MEM_LIMIT
          value: 3Gi
        - name: PAAS
          value: "false"
        - name: C8CEP_URL
          value: http://c8cep.c8:8080/_cep
        image: datawire/telepresence-k8s:0.105
        imagePullPolicy: Always
        name: c8db-coord
        ports:
        - containerPort: 8529
          name: server
          protocol: TCP
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-01-05T07:21:06Z"
    lastUpdateTime: "2023-01-05T07:21:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-01-05T07:20:50Z"
    lastUpdateTime: "2023-01-05T07:21:06Z"
    message: ReplicaSet "c8db-coord-79c56ff769" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
